### PR TITLE
Replaced qmake with CMake

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes: #13

### CODE REVIEW

**Comment by KOLANICH** [comment]
@hello-adam

**Comment by hello-adam** [comment]
Thanks for pinging, I haven't looked at this in a while. By the way, the python binding/integration has some new business use-cases for us, so I'm going to try to tackle that in the next few weeks.

**Comment by hello-adam** [comment]
I'm going to give this a shot now. Might take a few days, I'm not getting paid to work on this anymore, haha

**Comment by KOLANICH** [comment]
This PR got broken somewhen (I don't remember exactly when, likely somewhen in October). I have tried fo fix it multiple times but got compile errors. Both in clang++-12 and gcc-10. IDK if it is because of some not very well solved merge conflict, or anything else. Also CMake script for python + interpreter and stdlib discovery in the C++ sources needs some attention - I haven't tested it at all, it turned out that the CPack package for python plugin for Ubuntu doesn't . Currently I am not working on it, but it is not forgotten, I need this software (+ Kaitai plugin) for one of my researches. But you know this code base better than me, feel free to fix that before me ;)

>I'm not getting paid to work on this anymore, haha

Do you mean that development of this software has almost ended?

**Comment by hello-adam** [comment]
Thanks for the tips on what to look for. One thing I found was a weird template thing I was doing that seems to have gone from a warning in the old build to an error in this one. I'll let you know if I get stuck on anything in the CMake portion.

> Do you mean that development of this software has almost ended?

I plan on continuing to work on this - it won't get as much attention as before, but I'm not really sure it needs a lot more constant development (it seems more idea and use-case constrained than capability constrained at the moment.) I'm also going to be using it in my community education efforts, so I'll be paying high school and college students to develop on it.

Mahlet also might invest more in it, I'm not sure what their plans are right now.

**Pull request merged**
