### PR TITLE
Use versionless Qt cmake targets

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Qt 5.15 introduced versionless package detection. In the future this may allow for Qt 5 & Qt6 compatibility.

https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
This replaces https://github.com/Mahlet-Inc/hobbits/pull/163

**Comment by hello-adam** [comment]
I guess the build pipeline uses 5.12 so this won't work. I think the solution is to add a job for a newer platform for both Qt 5.15 and Qt 6. I don't think it's a good idea to end support for the current 5.12 build yet.

**Comment by hello-adam** [comment]
On second thought, I guess it doesn't make sense to make this simplification until the build only supports 5.15+ - hmmm, maybe I'll just do that soonish. Anyone needing the old compatibility would likely be able to use an old tag more easily than a dev with newer Qt toolchains installed that is actively trying to add or modify something.

**Comment by antoniovazquezblanco** [comment]
Just for future reference one may find the available qt versions of different platforms in:
https://packages.ubuntu.com/search?keywords=qt5
https://packages.debian.org/search?keywords=qt5
https://packages.fedoraproject.org/pkgs/qt5-doc/qt5-doc/
https://software.opensuse.org/package/libqt5-qtbase

At the time of writing this comment, the only platforms that do not yet ship Qt 5.15 are:
Ubuntu Focal 20.04LTS

**Comment by antoniovazquezblanco** [comment]
@hello-adam how are you doing?

It seems there is not much movement regarding hobbits. It's been almost a year and no functionality seems to get pushed. I guess that this means that making hobbits Qt6 compatible can help package maintainers while not punishing users.

How do you feel about going Qt versionless with Qt > 5.15 minimum requirement now?

Thanks!

**Comment by hello-adam** [comment]
Thanks for the reminder! I'll set up a newer build environment and give this another shot. I've also noticed that the released *.deb package doesn't find the plugins correctly, so I'll try to fix that as well while I'm at it.

**Comment by hello-adam** [comment]
seemed to work fine, thanks a bunch @antoniovazquezblanco

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
